welc = """
Ex1 to Ex20, only easy and medium problem
Usage:
    - ex[1..20]: to run equivalent exercise
    - exit: quit the program
"""
output  = "stdout"
input   = "stdin"

[loop]
    end   = "exit"
    print = "Exercise: "
    [[loop.sw]]
        #Find a pair with the given sum in an array
        handler = "ex1"
        args    = ["arr", "target"]
        desc    = ["Input Arr: ", "Input the sum: "]
    [[loop.sw]]
        #Check if a sub array with 0 sum exists or not
        handler = "ex2"
        args    = ["arr"]
        desc    = []
    [[loop.sw]]
        #Print all sub arrays with 0 sum
        handler = "ex3"
        args    = ["arr"]
        desc    = []
    [[loop.sw]]
        #Sort binary array in linear time O(N) and constant space
        #[0,1,1,0,0,1,0] -> [0,0,0,0,1,1,1]
        handler = "ex4"
        args    = ["arr"]
        desc    = []